# Generated by Django 3.0.3 on 2020-02-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0004_auto_20200205_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='uniq_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
