# Generated by Django 3.0.3 on 2020-03-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0009_uservideo_email_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='convert_state',
            field=models.IntegerField(default=0, verbose_name='estado video'),
        ),
    ]
