# Generated by Django 3.0.3 on 2020-02-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0002_auto_20200205_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='prize_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='uniq_url',
            field=models.URLField(max_length=50, unique=True),
        ),
    ]
