# Generated by Django 3.0.3 on 2020-02-08 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0005_auto_20200205_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, verbose_name='user email')),
                ('video_file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'flv', 'avi', 'wmv'])])),
                ('message', models.TextField(max_length=100)),
                ('convert_state', models.BooleanField(verbose_name='estado video')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concurso', to='concursos.Concurso')),
            ],
        ),
    ]
