# Generated by Django 3.0.3 on 2020-02-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0006_uservideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='convert_state',
            field=models.BooleanField(default=False, verbose_name='estado video'),
        ),
    ]
