# Generated by Django 3.0.3 on 2020-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0008_uservideo_video_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='email_send',
            field=models.BooleanField(default=False),
        ),
    ]
