# Generated by Django 3.0.3 on 2020-03-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0010_auto_20200329_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='email_send',
            field=models.IntegerField(default=0, verbose_name='estado email'),
        ),
    ]
